language: go

services:
  - mongodb

go:
  - 1.6
  - 1.7

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

install:
  - mkdir -p $GOPATH/src/gopkg.in/src-d
  - cp -rf $PWD $GOPATH/src/gopkg.in/src-d/storable.v1
  - go get -t -v ./...

script:
  - go generate ./...
  - go test -v gopkg.in/src-d/storable.v1/generator
  - go test -v gopkg.in/src-d/storable.v1 -covermode=count -coverprofile=coverage.out
  - go test -v gopkg.in/src-d/storable.v1/operators -covermode=count -coverprofile=tmp.out
  - tail -n +2 tmp.out >> coverage.out
  - go test -v gopkg.in/src-d/storable.v1/tests -covermode=count -coverprofile=tmp.out
  - tail -n +2 tmp.out >> coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

